[INPUT]
    Name              tail
    Tag               app.stdout
    Path              /var/log/supervisor/app.stdout.log
    DB                /var/log/fluent-bit/app-stdout.db
    Read_from_Head    false
    Refresh_Interval  5
    Rotate_Wait       10
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Tag               app.stderr
    Path              /var/log/supervisor/app.stderr.log
    DB                /var/log/fluent-bit/app-stderr.db
    Read_from_Head    false
    Refresh_Interval  5
    Rotate_Wait       10
    Skip_Long_Lines   On

[INPUT]
    Name               nginx_metrics
    Tag                nginx.status
    Status_Url         http://127.0.0.1/nginx_status
    Nginx_Plus         Off

[OUTPUT]
    Name              prometheus_exporter
    Match             nginx.status
    Host              0.0.0.0
    Port              2020

[OUTPUT]
    Name              stdout
    Match             app.*
